export const TOP_SUBSCRIPTIONS = [
  'ChatGPT',
  'Netflix',
  'Spotify',
  'YouTube Premium',
  'Amazon Prime (full membership)',
  'Disney+ Hotstar',
  'Canva',
  'Microsoft 365',
  'Adobe Creative Cloud',
  'Grammarly',
] as const;

export const ALL_SUBSCRIPTIONS = [
  'ChatGPT',
  'Netflix',
  'Spotify',
  'Canva',
  'Amazon Prime Video',
  'Disney+ Hotstar',
  'YouTube Premium',
  'Sony LIV',
  'ZEE5',
  'Apple Music',
  'Amazon Prime (full membership)',
  'Microsoft 365',
  'Google One',
  'Notion',
  'Grammarly',
  'Adobe Creative Cloud',
  'Figma (Professional)',
  'CapCut Pro',
  'Coursera Plus',
  'Udemy Business',
  'GitHub Copilot',
  'JetBrains All Products Pack',
  'Dropbox',
] as const;
